---
- name: install ppa dependencies
  apt:
    name:
      - ca-certificates
      - gnupg
      - software-properties-common
      - apt-transport-https
    update_cache: yes
  become: "yes"

- name: enable emacs ppa
  apt_repository:
    repo: ppa:kelleyk/emacs
    update_cache: yes
  become: "yes"
