---
- name: os-specific variables
  ansible.builtin.include_tasks: variables.yml

- name: install emacs
  ansible.builtin.package:
    name: "{{ emacs_packages }}"
  become: "{{ __emacs_install_become | default('yes') }}"
